@baseUrl = http://localhost:3001/api/v1
@contentType = application/json

# Save variables manually
@accessToken = YOUR_ACCESS_TOKEN_HERE
@watchlistId = YOUR_WATCHLIST_ID_HERE
@movieId = YOUR_MOVIE_ID_HERE

### ----------------------------------------------------------------
### AUTH MODULE
### ----------------------------------------------------------------

### 1. Register User
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "name": "Cyrene",
  "email": "cyrene@hoyohsr.com",
  "password": "#Rene321"
}

### 2. Login User
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "cyrene@hoyohsr.com",
  "password": "#Rene321"
}

### 3. Get Current User Profile (Me)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{accessToken}}

### 4. Refresh Token
POST {{baseUrl}}/auth/refresh

### 5. Logout User
POST {{baseUrl}}/auth/logout

### ----------------------------------------------------------------
### WATCHLIST MODULE (Requires Bearer Access Token)
### ----------------------------------------------------------------

### 1. Add Item to Watchlist
POST {{baseUrl}}/watchlists
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "movieId": "{{movieId}}",
  "status": "WATCHING",
  "rating": 5,
  "notes": "The movie is excellent!"
}

### 2. Get Watchlist Items (Default Page 1, Limit 10)
GET {{baseUrl}}/watchlists
Authorization: Bearer {{accessToken}}

### 3. Get Watchlist Items with Filter & Pagination
GET {{baseUrl}}/watchlists?status=WATCHING&page=1&limit=5
Authorization: Bearer {{accessToken}}

### 4. Edit Watchlist Item
PUT {{baseUrl}}/watchlists/{{watchlistId}}
Authorization: Bearer {{accessToken}}
Content-Type: {{contentType}}

{
  "status": "COMPLETED",
  "rating": 5,
  "notes": "Finished watching it."
}

### 5. Delete Watchlist Item
DELETE {{baseUrl}}/watchlists/{{watchlistId}}
Authorization: Bearer {{accessToken}}
