@baseUrl = http://localhost:3001/api/v1

###

GET {{baseUrl}}/health

###

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Khaslana",
  "email": "khaslana@hoyohsr.com",
  "password": "#Khas123"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "stelle@hoyohsr.com",
  "password": "#Stelle1"
}

###

GET {{baseUrl}}/movies

###

POST {{baseUrl}}/movies

###

# @name addWatchlistItem
POST {{baseUrl}}/watchlists
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "movieId": ""
}

###

# @name editWatchlistItem
PUT {{baseUrl}}/watchlists/:id
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}

{
  "status": "COMPLETED",
  "rating": null,
  "notes": null
}

###

# @name deleteWatchlistItem
DELETE  {{baseUrl}}/watchlists/:id
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.token}}
